## **Create NumPy Arrays**

### **Table of Contents** ###

- **Install and Import Numpy**
- **Create NumPy Arrays**
  - `np.array()`
  - `np.arange()`
  - `np.linspace()`

### **Install and Import Numpy**

In [68]:
# !pip install numpy

In [69]:
import numpy as np

### **Create NumPy Arrays**

##### **`np.array()`**

In [5]:
# Create and print a NumPy array 'a' containing the elements 1, 2, 3.
a = np.array([1, 2, 3])
print(a)

[1 2 3]


##### **`np.arange()`**

Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval.

In [3]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [6]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


##### **`np.linspace()`**

Create an array with five evenly spaced values in the interval from 0 to 100?

In [33]:
lin_spaced_arr = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr)

[  0  25  50  75 100]
