## **Attributes of NumPy Arrays**


### **Table of Contents** ###

- **Introduction**
- **Creating Multidimensional Arrays**
- **Finding Dimension, Shape, Size, Data-Type, ItemSize and Num of Bytes**
  - `ndarray.ndim`
  - `ndarray.shape`
  - `ndarray.size`
  - `ndarray.dtype`
  - `ndarray.itemsize`
  - `ndarray.nbytes`
- **Function to Analyze Array Attributes**

---

### **Introduction** ###
NumPy arrays have several useful attributes that help us understand their structure, including dimensions, shape, size, and data type. This notebook explores these attributes with examples.

In [58]:
import numpy as np

### **Creating a NumPy Array** ###
Let's create a simple 2D NumPy array to explore its attributes.

In [59]:
# Create a 2D array (2 rows, 3 columns)
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


### **Finding Dimension, Shape, Size, Data-Type, ItemSize and Num of Bytes**

##### **Number of Dimensions**

`ndarray.ndim` stores the number of dimensions of the array.

In [60]:
print("ndim:", a.ndim)

ndim: 2


##### **Shape of the Array**

`ndarray.shape` returns a tuple representing the shape (rows, columns) of the array.


In [61]:
print("Shape (rows, columns):", a.shape)

Shape (rows, columns): (2, 3)


##### **Total Number of Elements**

`ndarray.size` returns the total number of elements in the array.

In [62]:
print("Size:", a.size)

Size: 6


##### **Data Type of Elements**

`ndarray.dtype` shows the data type of the elements in the array.

In [63]:
print("dtype:", a.dtype)

dtype: int32


##### **Memory Usage Information**

**Item Size:**

`ndarray.itemsize` returns the memory size (in bytes) of each element in the array.

In [64]:
print("Item size (bytes per element):", a.itemsize)

Item size (bytes per element): 4


**Total Size of the Array in Bytes:**

`ndarray.nbytes` calculates the total memory size occupied by the array.


In [73]:
print("Total memory size (bytes):", a.nbytes)
print("Total memory size (bytes):", (a.size * a.itemsize))

Total memory size (bytes): 24
Total memory size (bytes): 24


---

### **Function to Analyze Array Attributes**

In [66]:
def analyze_array(arr):
    print("Array:\n", arr)
    print("\nNumber of dimensions (ndim):", arr.ndim)
    print("Shape:", arr.shape)
    print("Total number of elements (size):", arr.size)
    print("Data type (dtype):", arr.dtype)
    print("Item size (bytes per element):", arr.itemsize)
    print("Total memory size (bytes):", arr.nbytes)

In [67]:
# Create a 1D array (5 elements)
b = np.array([1, 2, 3, 4, 5])

# Analyze the array
analyze_array(b)

Array:
 [1 2 3 4 5]

Number of dimensions (ndim): 1
Shape: (5,)
Total number of elements (size): 5
Data type (dtype): int32
Item size (bytes per element): 4
Total memory size (bytes): 20


In [68]:
# Create a 2D array (3 rows, 4 columns)
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Analyze the array
analyze_array(c)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Number of dimensions (ndim): 2
Shape: (3, 4)
Total number of elements (size): 12
Data type (dtype): int32
Item size (bytes per element): 4
Total memory size (bytes): 48


In [69]:
# Create a 3D array (2 blocks, 3 rows, 4 columns)
d = np.array(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)

# Analyze the array
analyze_array(d)

Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Number of dimensions (ndim): 3
Shape: (2, 3, 4)
Total number of elements (size): 24
Data type (dtype): int32
Item size (bytes per element): 4
Total memory size (bytes): 96
