## **More Functions to Create NumPy Arrays**

NumPy provides various functions to create arrays easily, including ones filled with specific values or random numbers.


### **Table of Contents** ###

- **Creating Arrays with Specific Values**
  - `np.ones()`
  - `np.zeros()`
  - `np.full()`
  - `np.empty()`
- **Creating Random Arrays**
  - `np.random.rand()`
  - `np.random.random()`
  - `np.random.randint()`
  - `np.random.normal()`
- **Creating Identity and Diagonal Matrices**
  - `np.eye()`
  - `np.diag()`

In [2]:
import numpy as np

---

### **Creating Arrays with Specific Values** ###

##### **`np.ones()`**

In [3]:
# Creates an array filled with ones.
ones_arr = np.ones(3)
print("Ones Array:\n", ones_arr)

Ones Array:
 [1. 1. 1.]


##### **`np.zeros()`**

In [4]:
# Creates an array filled with zeros.
zeros_arr = np.zeros(3)
print("Zeros Array:\n", zeros_arr)

Zeros Array:
 [0. 0. 0.]


##### **`np.full()`**

In [5]:
# Creating an array filled with a constant value
a = np.full((2, 3), 5)
print("Full Array:\n", a)

Full Array:
 [[5 5 5]
 [5 5 5]]


##### **`np.empty()`**

In [6]:
# Creates an uninitialized array of given shape.
empty_arr = np.empty(3)
print("Empty Array:\n", empty_arr)

Empty Array:
 [1. 1. 1.]


---

### **Creating Random Arrays**

##### **`np.random.rand()`**

In [7]:
# Generates random floating-point numbers between 0 and 1.
rand_arr = np.random.rand(3)
print("Random Array (rand):\n", rand_arr)

Random Array (rand):
 [0.60201348 0.56802377 0.59910824]


##### **`np.random.random()`**

In [8]:
# Generates random floating-point numbers between 0 and 1.
rand_random_arr = np.random.random(3)
print("Random Array (random):\n", rand_random_arr)

Random Array (random):
 [0.80730082 0.16467785 0.18710266]


##### **Difference Between `np.random.rand(3)` and `np.random.random(3)`**
- Both generate random numbers between 0 and 1.
- Difference in syntax:
  - `np.random.rand()` uses arguments without parentheses.
  - `np.random.random()` uses arguments inside parentheses.

##### **`np.random.randint()`**

In [9]:
# Generates random integers within a specified range.
rand_int_arr = np.random.randint(low=10, high=50, size=3)
print("Random Integer Array:\n", rand_int_arr)

Random Integer Array:
 [43 36 21]


##### **`np.random.normal()`**

Generates random numbers sampled from a normal (Gaussian) distribution.

In [10]:
# Generate an array of 3 random numbers with a mean of 0 and a standard deviation of 1.
rand_normal_arr = np.random.normal(loc=0, scale=1, size=3)
print("Random Normal Array:\n", rand_normal_arr)

Random Normal Array:
 [-0.63137561  1.6418319  -1.01857842]


- `loc`: Mean
- `scale`: Standard deviation
- `size`: Array size

---

### **Creating Identity and Diagonal Matrices**


##### **`np.eye()`**

In [18]:
# Creating an identity matrix
identity_matrix = np.eye(3, dtype=int)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


##### **`np.diag()`**

Creates a diagonal matrix with specified values.

In [16]:
diag_arr = np.diag([1, 5, 9])
print("Diagonal Matrix:\n", diag_arr)

Diagonal Matrix:
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


In [19]:
diag_arr = np.diag([1, 1, 1])
print("Diagonal Matrix:\n", diag_arr)

Diagonal Matrix:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
