## **Save and Load NumPy Array**


In [13]:
import numpy as np

In [14]:
# Create a NumPy array
np_array = np.arange(12).reshape((3, 4))
print("Original Array:\n", np_array)

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### **Saving a NumPy Array**

NumPy provides the `np.save()` function to save an array to a `.npy` file.

In [15]:
# Save the array to a file
np.save("np_array.npy", np_array)
print("Array saved to 'np_array.npy'")

Array saved to 'np_array.npy'


### **Loading a NumPy Array**
To load a saved NumPy array from a `.npy` file, use the `np.load()` function.

In [16]:
# Load the array from the file
loaded_array = np.load("np_array.npy")
print("Loaded Array:\n", loaded_array)

Loaded Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
