## **Views and Copies in NumPy**

In [21]:
import numpy as np

### **Table of Contents**
1. **View (Shallow Copy)**
2. **Practical Example: Modifying a Subarray**
3. **Deep Copy**

---

### **View (Shallow Copy)**

A **view** is a shallow copy of an array. It creates a new array object that shares the same data as the original array. This means that modifying the view will also modify the original array.

In [22]:
# Create an array
original_array = np.array([1, 2, 3, 4, 5])

# Create a view of the array
view_array = original_array.view()

print("Original Array:", original_array)
print("View Array:", view_array)

Original Array: [1 2 3 4 5]
View Array: [1 2 3 4 5]


In [31]:
# Modify the view and original array
original_array[0] = 100
view_array[-1] = 200

print("After modifying the view and original array:")
print("\nOriginal Array:", original_array)
print("View Array:", view_array)

After modifying the view and original array:

Original Array: [100   2   3   4 200]
View Array: [100   2   3   4 200]


---

### **Practical Example: Modifying a Subarray**

When working with subarrays, it’s important to understand whether you’re creating a view or a copy. By default, slicing an array creates a **view**, which means modifying the subarray will also modify the original array.

In [24]:
# Create a 2D array
array_2d = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
print("Original Array:\n", array_2d)

Original Array:
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [25]:
# Create a subarray (this is a view)
sub_array = array_2d[:2, :2]
print("Subarray (View):\n", sub_array)

Subarray (View):
 [[12  5]
 [ 7  6]]


In [34]:
# Modify the subarray and original array
array_2d[0, 0] = 100
sub_array[0, 1] = 200

print("After modifying the subarray and original array:\n")
print("Original Array:\n", array_2d)
print("\nSubarray (View):\n", sub_array)

After modifying the subarray and original array:

Original Array:
 [[100 200   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]

Subarray (View):
 [[100 200]
 [  7   6]]


---

### **Deep Copy**

A **deep copy** creates a completely independent copy of the array. Changes made to the deep copy do not affect the original array, and vice versa.

In [27]:
# Create an array
original_array = np.array([1, 2, 3, 4, 5])

# Create a deep copy of the array
deep_copy_array = original_array.copy()

print("Original Array:", original_array)
print("Deep Copy Array:", deep_copy_array)

Original Array: [1 2 3 4 5]
Deep Copy Array: [1 2 3 4 5]


In [36]:
# Modify the deep copy and original array
original_array[-1] = 200
deep_copy_array[0] = 100

print("After modifying the deep copy and original array:\n")
print("Original Array:", original_array)
print("Deep Copy Array:", deep_copy_array)

After modifying the deep copy and original array:

Original Array: [100   2   3   4 200]
Deep Copy Array: [100   2   3   4   5]
