## **NumPy Array Shape Manipulation**


### **Table of Contents**
- Introduction
- Reshaping Arrays
  - `np.reshape()`
- Flattening Arrays
  - `np.ravel()`
- Removing Single-Dimension Entries
  - `np.squeeze()`

---

### **Introduction**
NumPy provides powerful functions to manipulate array shapes efficiently. You can reshape arrays, flatten them, and remove unnecessary dimensions easily.

In [31]:
import numpy as np

### **Reshaping Arrays**

##### **`np.reshape()`:** Used to change the shape of an array without modifying its data.


**Example:** Reshape a 1D array into 2D and 3D.


In [32]:
original_array = np.arange(24)
print("Original array:")
print(original_array)
print("Shape:", original_array.shape)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)


In [33]:
# Reshape to (3,8)
reshaped_3_8 = original_array.reshape((3, 8))
print("Reshaped to (3,8):\n", reshaped_3_8)
print("Shape:", reshaped_3_8.shape)

Reshaped to (3,8):
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
Shape: (3, 8)


In [34]:
# Reshape to (2,3,4)
reshaped_3d = original_array.reshape((2, 3, 4))
print("Reshaped to (2,3,4):\n", reshaped_3d)
print("Shape:", reshaped_3d.shape)

Reshaped to (2,3,4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)


---

### **Flattening Arrays**

##### **`np.ravel()`:** Returns a 1D flattened array from any multi-dimensional array.

**Example:** Flatten a 3D array.

In [35]:
print("3D Array:\n", reshaped_3d)

3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [36]:
flattened_array = reshaped_3d.ravel()
print("Flattened array:\n", flattened_array)
print("Shape:", flattened_array.shape)

Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)


---

### **Removing Single-Dimension Entries**

##### **`np.squeeze()`**
- Removes axes with size 1 from an array.
- `np.squeeze(arr, axis=n)` removes a specific axis if its size is 1.

In [37]:
# Example 1: Remove all single-dimension axes
a = np.arange(24).reshape(1, 24, 1)
squeezed_a = np.squeeze(a)
print("Original shape:", a.shape)
print("Shape after squeeze:", squeezed_a.shape)

Original shape: (1, 24, 1)
Shape after squeeze: (24,)


In [38]:
# Example 2: Remove axis 0 only
a = np.arange(24).reshape(1, 6, 4)
squeezed_a = np.squeeze(a, axis=0)
print("Original shape:", a.shape)
print("Shape after squeezing axis 0:", squeezed_a.shape)

Original shape: (1, 6, 4)
Shape after squeezing axis 0: (6, 4)


In [39]:
# Example 3: Remove axis 2 only
a = np.arange(24).reshape(1, 24, 1)
squeezed_a = np.squeeze(a, axis=2)
print("Original shape:", a.shape)
print("Shape after squeezing axis 2:", squeezed_a.shape)

Original shape: (1, 24, 1)
Shape after squeezing axis 2: (1, 24)


In [40]:
# Example 4: Attempt to remove a non-singleton axis (no change)
a = np.arange(24).reshape(2, 3, 4)
squeezed_a = np.squeeze(a)
print("Original shape:", a.shape)
print("Shape after squeeze (unchanged):", squeezed_a.shape)

Original shape: (2, 3, 4)
Shape after squeeze (unchanged): (2, 3, 4)
