## **Indexing and Slicing**


### **Table of Contents**

1. **Indexing**
   - Indexing in 1D Arrays
   - Indexing in 2D Arrays
2. **Slicing**
   - Slicing in 1D Arrays
   - Slicing in 2D Arrays

---

In [3]:
import numpy as np

### **1. Indexing**


#### **1.1 Indexing in 1D Arrays**


Indexing allows you to access specific elements in an array. In 1D arrays, you use a single index to access an element.

In [38]:
# Create a 1D array
one_dim = np.arange(1, 11)
print("1D Array:", one_dim)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]


In [39]:
# Select the third element (index 2)
print("Third element:", one_dim[2])

Third element: 3


In [40]:
# Select the first element (index 0)
print("First element:", one_dim[0])

First element: 1


In [41]:
# Select the last element (index -1)
print("Last element:", one_dim[-1])

Last element: 10


#### **1.2 Indexing in 2D Arrays**


- For multidimensional arrays of shape `n`, to index a specific element, you must input `n` indices, one for each dimension.

- In 2D arrays, you need to provide two indices: one for the row and one for the column.



In [42]:
# Create a 2D array
two_dim = np.arange(1, 10).reshape((3, 3))
print("2D Array:\n", two_dim)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
# Select element number 8 (row 2, column 1)
print("Element at [2, 1]:", two_dim[2, 1])

Element at [2, 1]: 8


In [44]:
# Select element number 3 (row 0, column 2)
print("Element at [0, 2]:", two_dim[0, 2])

Element at [0, 2]: 3


---

### **2. Slicing**


#### **2.1 Slicing in 1D Arrays**


Slicing allows you to extract a portion of an array. The syntax is:

`array[start:end:step]`

- start: The starting index (inclusive). Default is 0.
- end: The ending index (exclusive). Default is the length of the array.
- step: The step size. Default is 1.

In [58]:
print("1D Array:\n", one_dim)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [59]:
# Slice the array to get [2, 3, 4]
print(one_dim[1:4])

[2 3 4]


In [48]:
# Slice the array to get [1, 2, 3]
print(one_dim[:3])

[1 2 3]


In [50]:
# Slice the array to get elements from index 2 to the end
print(one_dim[2:])

[ 3  4  5  6  7  8  9 10]


In [52]:
# Slice the array to get every second element
print("Slice with step 2:", one_dim[::2])

Slice with step 2: [1 3 5 7 9]


#### **2.2 Slicing in 2D Arrays**


In 2D arrays, slicing works similarly, but you need to specify slices for both rows and columns. The syntax is:

`array[start_row:end_row:step, start_col:end_col:step]`

In [60]:
print("2D Array:\n", two_dim)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
# Slice the array to get the first two rows
print("First two rows:\n", two_dim[:2])

First two rows:
 [[1 2 3]
 [4 5 6]]


In [54]:
# Slice the array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print("Last two rows:\n", sliced_two_dim_rows)

Last two rows:
 [[4 5 6]
 [7 8 9]]


In [55]:
# Slice the array to get the first column
sliced_two_dim_cols = two_dim[:, 0]
print("First column:\n", sliced_two_dim_cols)

First column:
 [1 4 7]


In [56]:
# Slice the array to get every second row and column
print("Every second row and column:\n", two_dim[::2, ::2])

Every second row and column:
 [[1 3]
 [7 9]]
