### **Stacking in NumPy**


In [39]:
import numpy as np


### **Table of Contents**
1. **Introduction to Stacking**
2. **Vertical Stacking (`np.vstack()`)**
3. **Horizontal Stacking (`np.hstack()`)**

---

### **Introduction to Stacking**


Stacking is a powerful feature in NumPy that allows you to combine two or more arrays either **vertically** or **horizontally**. This is done along a new axis, providing increased flexibility in array manipulation.

---

### **Vertical Stacking (`np.vstack()`)**

- Vertical stacking combines arrays row-wise. 
- The arrays must have the same number of columns.

In [40]:
# Example 1: Stacking 1D arrays vertically
vert_stack_1d = np.vstack((np.array([1, 2, 3]), np.array([4, 5, 6])))
print("Vertical Stack (1D arrays):\n", vert_stack_1d)

Vertical Stack (1D arrays):
 [[1 2 3]
 [4 5 6]]


In [41]:
# Example 2: Stacking 2D arrays vertically
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

print("Array 1:\n", a1)
print("\nArray 2:\n", a2)

Array 1:
 [[1 1]
 [2 2]]

Array 2:
 [[3 3]
 [4 4]]


In [42]:
vert_stack_2d = np.vstack((a1, a2))
print("Vertical Stack (2D arrays):\n", vert_stack_2d)

Vertical Stack (2D arrays):
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]


---

### **Horizontal Stacking (`np.hstack()`)**
- Horizontal stacking combines arrays column-wise. 
- The arrays must have the same number of rows.

In [43]:
# Example 1: Stacking 1D arrays horizontally
horz_stack_1d = np.hstack((np.array([1, 2, 3]), np.array([4, 5, 6])))
print("Horizontal Stack (1D arrays):\n", horz_stack_1d)

Horizontal Stack (1D arrays):
 [1 2 3 4 5 6]


In [44]:
# Example 2: Stacking 2D arrays horizontally
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

print("Array 1:\n", a1)
print("\nArray 2:\n", a2)

Array 1:
 [[1 1]
 [2 2]]

Array 2:
 [[3 3]
 [4 4]]


In [45]:
horz_stack_2d = np.hstack((a1, a2))
print("Horizontal Stack (2D arrays):\n", horz_stack_2d)

Horizontal Stack (2D arrays):
 [[1 1 3 3]
 [2 2 4 4]]
