## **Splitting NumPy Arrays**

**Reference:** https://numpy.org/doc/stable/reference/generated/numpy.split.html

In [79]:
import numpy as np

### **Table of Contents**
1. **Introduction to Splitting**
2. **Functions for Splitting**
   - `np.split()`
   - `np.hsplit()`
   - `np.vsplit()`

---

### **1. Introduction to Splitting**

Splitting is the process of dividing a NumPy array into multiple subarrays. This is useful for tasks like data preprocessing, cross-validation, or dividing data into training and testing sets.

NumPy provides several functions for splitting arrays:
- `np.split()`: Splits an array into multiple subarrays along a specified axis.
- `np.hsplit()`: Splits an array horizontally (column-wise).
- `np.vsplit()`: Splits an array vertically (row-wise).

---

### **2. Functions for Splitting**


#### **2.1 `np.split()`**

The `np.split()` function splits an array into multiple subarrays along a specified axis. You can specify the indices where the splits should occur.

In [48]:
# Create a 1D array
array_1d = np.arange(10)
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


In [68]:
# Split the array at indices [2, 3, 7]
split_arrays = np.split(array_1d, indices_or_sections=[2, 3, 7])

print("Split Arrays:")
for i, arr in enumerate(split_arrays):
    print(f"Part {i+1}:", arr)

Split Arrays:
Part 1: [0 1]
Part 2: [2]
Part 3: [3 4 5 6]
Part 4: [7 8 9]


In [69]:
# N split points lead to N + 1 subarrays
s1, s2, s3, s4 = np.split(array_1d, [2, 3, 7])
print("Unpacked Split Arrays:")
print("Part 1:", s1)
print("Part 2:", s2)
print("Part 3:", s3)
print("Part 4:", s4)

Unpacked Split Arrays:
Part 1: [0 1]
Part 2: [2]
Part 3: [3 4 5 6]
Part 4: [7 8 9]


---

#### **2.2 `np.hsplit()`**
The `np.hsplit()` function splits an array horizontally (column-wise). You can specify the number of sections or the column indices where the splits should occur.

In [51]:
# Create a 2D array
array_2d = np.arange(16).reshape((4, 4))
print("2D Array:\n", array_2d)

2D Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [71]:
# Split the array horizontally into 2 equal parts
hsplit_arrays = np.hsplit(array_2d, indices_or_sections=2)
print("Horizontally Split Arrays (2 equal parts):")
for i, arr in enumerate(hsplit_arrays):
    print(f"Part {i+1}:\n", arr)

Horizontally Split Arrays (2 equal parts):
Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [73]:
# Split the array at columns 1 and 3
hsplit_arrays = np.hsplit(array_2d, indices_or_sections=[1, 3])
print("Horizontally Split Arrays (at columns 1 and 3):")
for i, arr in enumerate(hsplit_arrays):
    print(f"Part {i+1}:\n", arr)

Horizontally Split Arrays (at columns 1 and 3):
Part 1:
 [[ 0]
 [ 4]
 [ 8]
 [12]]
Part 2:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Part 3:
 [[ 3]
 [ 7]
 [11]
 [15]]


---

#### **2.3 `np.vsplit()`**
The `np.vsplit()` function splits an array vertically (row-wise). You can specify the number of sections or the row indices where the splits should occur.

In [74]:
# Create a 2D array
array_2d = np.arange(16).reshape((4, 4))
print("2D Array:\n", array_2d)

2D Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [76]:
# Split the array vertically into 2 equal parts
vsplit_arrays = np.vsplit(array_2d, indices_or_sections=2)
print("Vertically Split Arrays (2 equal parts):")
for i, arr in enumerate(vsplit_arrays):
    print(f"Part {i+1}:\n", arr)

Vertically Split Arrays (2 equal parts):
Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [78]:
# Split the array at rows 1 and 3
vsplit_arrays = np.vsplit(array_2d, indices_or_sections=[1, 3])
print("Vertically Split Arrays (at rows 1 and 3):")
for i, arr in enumerate(vsplit_arrays):
    print(f"Part {i+1}:\n", arr)

Vertically Split Arrays (at rows 1 and 3):
Part 1:
 [[0 1 2 3]]
Part 2:
 [[ 4  5  6  7]
 [ 8  9 10 11]]
Part 3:
 [[12 13 14 15]]
