## **Broadcasting in NumPy**

In [ ]:
import numpy as np

### **Table of Contents**
1. **Introduction to Broadcasting**
2. **Rules of Broadcasting**
3. **Practical Examples**
   - Example 1: Broadcasting a Scalar to an Array
   - Example 2: Broadcasting a 1D Array to a 2D Array
   - Example 3: Broadcasting a 1D Array to a 2D Array (Different Shapes)
   - Example 4: Broadcasting with Mismatched Shapes
   - Example 5: Broadcasting Arrays with Different Dimensions
   - Example 6: Broadcasting Shapes `(3, 2)` and `(3,)`

---

### **1. Introduction to Broadcasting**

Broadcasting is a powerful feature in NumPy that allows arithmetic operations between arrays of different shapes. Instead of explicitly reshaping arrays to make them compatible, NumPy automatically broadcasts the smaller array across the larger one, making operations efficient and concise.

---

### **2. Rules of Broadcasting**

#### **Rule 1 - Align shapes from the right**

When comparing two shapes, you compare them **from the last dimension backward**.

**Example 1:**
Shape A: `(1, 3)`
Shape B: `(2, 3)`
Align from the right:

```
A: 1   3
B: 2   3
```

**Example:2**
Shape A: `(5, 1, 4)`
Shape B: ` (   3, 1)`
Align from the right:

```
A: 5   1   4
B:     3   1
```

---

#### **Rule 2 - Dimensions are compatible if:**

For each dimension (right-to-left):

* They are **equal**, or
* One of them is **1**

If neither of these is true → **Broadcasting error**.

---


#### **How dimensions expand during broadcasting**

Whenever a dimension is `1`, it can be **repeated (stretched)** to match the corresponding dimension in the other shape.

**Example:**

```
A shape: (5, 1)
B shape: (1, 4)
```

Broadcasted result:

```
(5, 4)
```

Because:

* `1 → 4`
* `1 → 5`

---

**Example:**

```
A shape: (5, 2, 4)
B shape: (1, 4)
```

Align from the right:

```
A: 5   2   4
B:     1   4
```

B expands to:

```
(1, 2, 4)
```

Final broadcast result:

```
(5, 2, 4)
```

---


For two arrays to be broadcastable, the following rules must be satisfied:
1. **Rule 1**: If the arrays have different numbers of dimensions, the shape of the smaller array is padded with ones on its **left side**.
2. **Rule 2**: If the shapes of the arrays do not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
3. **Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

---

### **3. Practical Examples**


#### **Example 1: Broadcasting a Scalar to an Array**

In [ ]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)
print("1D Array Shape:", array_1d.shape)

1D Array: [1 2 3 4]
1D Array Shape: (4,)


In [ ]:
# Add a scalar to the array (broadcasting)
result = array_1d + 10
print("After Broadcasting (Scalar Addition):", result)

After Broadcasting (Scalar Addition): [11 12 13 14]


##### **Explanation of Broadcasting Rules**

- **Shape of `array_1d`**: `(4,)`
- **Shape of scalar `10`**: `()` (scalar has no dimensions)
- **Rule 1**: The scalar is treated as a 1D array with shape `(1,)`.
- **Rule 2**: The scalar is stretched to match the shape of `array_1d`, becoming `[10, 10, 10, 10]`.
  - **Shape of `array_1d`**: `(4,)`
  - **Shape of scalar after stretching**: `(4,)`
- **Result**: The operation is applied.

---

#### **Example 2: Broadcasting a 1D Array to a 2D Array**

In [ ]:
# Create a 2D array
array_2d = np.ones((2, 3))
print("2D Array:\n", array_2d)
print("2D Array Shape:", array_2d.shape)

2D Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
2D Array Shape: (2, 3)


In [ ]:
# Create a 1D array
array_1d = np.arange(3)
print("1D Array:", array_1d)
print("1D Array Shape:", array_1d.shape)

1D Array: [0 1 2]
1D Array Shape: (3,)


In [ ]:
# Add the 1D array to the 2D array (broadcasting)
result = array_2d + array_1d
print("After Broadcasting (2D + 1D):\n", result)

After Broadcasting (2D + 1D):
 [[1. 2. 3.]
 [1. 2. 3.]]


##### **Explanation of Broadcasting Rules**
- **Shape of `array_2d`**: `(2, 3)`
- **Shape of `array_1d`**: `(3,)`
- **Rule 1**: The 1D array is treated as a 2D array with shape `(1, 3)`.
- **Rule 2**: The 1D array is stretched along the first dimension to match `array_2d`, becoming:
  ```
  [[0, 1, 2],
   [0, 1, 2]]
  ```
  - **Shape of `array_2d`**: `(2, 3)`
  - **Shape of `array_1d` after stretching**: `(2, 3)`
- **Result**: The operation is applied.

---

#### **Example 3: Broadcasting a 1D Array to a 2D Array**

In [ ]:
# Create a 2D array
array_2d = np.arange(3).reshape((3, 1))
print("2D Array:\n", array_2d)
print("2D Array Shape:", array_2d.shape)

2D Array:
 [[0]
 [1]
 [2]]
2D Array Shape: (3, 1)


In [ ]:
# Create a 1D array
array_1d = np.arange(3)
print("1D Array:", array_1d)
print("1D Array Shape:", array_1d.shape)

1D Array: [0 1 2]
1D Array Shape: (3,)


In [ ]:
# Add the 1D array to the 2D array (broadcasting)
result = array_1d + array_2d
print("After Broadcasting (2D + 1D):\n", result)

After Broadcasting (2D + 1D):
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


##### **Explanation of Broadcasting Rules**
- **Shape of `array_2d`**: `(3, 1)`
- **Shape of `array_1d`**: `(3,)`
- **Rule 1**: The 1D array is treated as a 2D array with shape `(1, 3)`.
- **Rule 2**: Both arrays are stretched to shape `(3, 3)`:
  - `array_2d` becomes:
    ```
    [[0, 0, 0],
     [1, 1, 1],
     [2, 2, 2]]
    ```
  - `array_1d` becomes:
    ```
    [[0, 1, 2],
     [0, 1, 2],
     [0, 1, 2]]
    ```
  - **Shape of `array_2d` after stretching**: `(3, 3)`
  - **Shape of `array_1d` after stretching**: `(3, 3)`
- **Result**: The operation is applied.

---


#### **Example 4: Broadcasting with Mismatched Shapes**

In [ ]:
# Create a 2D array
array_2d = np.arange(6).reshape((2, 3))
print("2D Array:\n", array_2d)
print("2D Array Shape:", array_2d.shape)

2D Array:
 [[0 1 2]
 [3 4 5]]
2D Array Shape: (2, 3)


In [ ]:
# Create a 2D array
array_2d_2 = np.arange(2).reshape((2, 1))
print("2D Array:\n", array_2d_2)
print("2D Array Shape:", array_2d_2.shape)

2D Array:
 [[0]
 [1]]
2D Array Shape: (2, 1)


In [ ]:
# Add the two arrays (broadcasting)
result = array_2d + array_2d_2
print("After Broadcasting (2D + 2D):\n", result)

After Broadcasting (2D + 2D):
 [[0 1 2]
 [4 5 6]]


##### **Explanation of Broadcasting Rules**
- **Shape of `array_2d`**: `(2, 3)`
- **Shape of `array_2d_2`**: `(2, 1)`
- **Rule 1**: Both arrays already have the same number of dimensions.
- **Rule 2**: The second array is stretched along the second dimension to match `array_2d`, becoming:
  ```
  [[0, 0, 0],
   [1, 1, 1]]
  ```
  - **Shape of `array_2d`**: `(2, 3)`
  - **Shape of `array_2d_2` after stretching**: `(2, 3)`
- **Result**: The operation is applied.

---


#### **Example 5: Broadcasting Arrays with Different Dimensions**

In [ ]:
# Create a 3D array
array_3d = np.arange(12).reshape((2, 3, 2))
print("3D Array:\n", array_3d)

3D Array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
# Create a 1D array
array_1d = np.arange(2)
print("1D Array:", array_1d)

1D Array: [0 1]


In [ ]:
# Add the 1D array to the 3D array (broadcasting)
result = array_3d + array_1d
print("After Broadcasting (3D + 1D):\n", result)

After Broadcasting (3D + 1D):
 [[[ 0  2]
  [ 2  4]
  [ 4  6]]

 [[ 6  8]
  [ 8 10]
  [10 12]]]


#### **Explanation of Broadcasting Rules**
- **Shape of `array_3d`**: `(2, 3, 2)`
- **Shape of `array_1d`**: `(2,)`
- **Rule 1**: The 1D array is treated as a 3D array with shape `(1, 1, 2)`.
- **Rule 2**: The 1D array is stretched along the first and second dimensions to match `array_3d`, becoming:
  ```
  [[[0, 1],
    [0, 1],
    [0, 1]],

   [[0, 1],
    [0, 1],
    [0, 1]]]
  ```
  - **Shape of `array_3d`**: `(2, 3, 2)`
  - **Shape of `array_1d` after stretching**: `(2, 3, 2)`
- **Result**: The operation is applied.

---


#### **Example 6: Broadcasting Shapes `(3, 2)` and `(3,)`**


In [ ]:
# Create a 2D array with shape (3, 2)
array_2d = np.arange(1, 7).reshape(3, 2)
print("2D Array (Shape (3, 2)):\n", array_2d)

2D Array (Shape (3, 2)):
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Create a 1D array with shape (3,)
array_1d = np.arange(3)
print("1D Array (Shape (3,)):", array_1d)

1D Array (Shape (3,)): [0 1 2]


In [ ]:
result = array_2d + array_1d
print("After Broadcasting (1D + 2D):\n", result)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

##### **Explanation of Broadcasting Rules**
- **Shape of `array_2d`**: `(3, 2)`
- **Shape of `array_1d`**: `(3,)`
- **Rule 1**: The 1D array is treated as a 2D array with shape `(1, 3)`.
- **Rule 2**: The 1D array is stretched along the first dimension to match `array_2d`, becoming:
  ```
  [[0, 1, 2],
   [0, 1, 2],
   [0, 1, 2]]
  ```
  - **Shape of `array_2d`**: `(3, 2)`
  - **Shape of `array_1d` after stretching**: `(3, 3)`
- **Rule 3**: Sizes in the second dimension disagree (2 vs. 3), and neither is 1 → **Broadcasting fails**.
- **Result** ValueError: operands could not be broadcast together with shapes `(3,2) (3,)`
---


![image.png](attachment:image.png)