# **NumPy Sorting**
**(`np.sort`, In-Place Sorting `array.sort()`, Inverse Sorting, and `np.argsort`)**

In [84]:
import numpy as np

---


## **Table of Contents**
1. **Functions for Sorting**
   - **2.1 `np.sort()`**
     - Examples for `np.sort()`
   - **2.2 In-Place Sorting `array.sort()`**
     - Examples for In-Place Sorting
   - **2.3 Inverse Sorting (Descending Order)**
     - Examples for Inverse Sorting
   - **2.4 `np.argsort()`**
     - Examples for `np.argsort()`
2. **Advanced Examples**
   - Sorting Structured Arrays

---

## **2. Functions for Sorting**

### **2.1 `np.sort()`**

The [`np.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) function returns a sorted copy of the input array. By default, it sorts along the last axis.

**Syntax:**
```python
np.sort(array, axis=-1, kind=None, order=None)
```

- **`array`**: Input array to be sorted.
- **`axis`**: Axis along which to sort. Default is `-1` (last axis).
- **`kind`**: Sorting algorithm (e.g., `'quicksort'`, `'mergesort'`, `'heapsort'`). Default is `'quicksort'`.
- **`order`**: For structured arrays, specifies the field to sort by.


In [85]:
# help(np.sort)

---

#### **Examples for `np.sort()`**


##### **Example 1: Sorting a 1D Array**


In [86]:
# Create a 1D array
array_1d = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("Original 1D Array:", array_1d)

Original 1D Array: [3 1 4 1 5 9 2 6 5]


In [ ]:
# Sort the array
sorted_array = np.sort(array_1d)
print("Sorted 1D Array:", sorted_array)
print("Original 1D Array After Sorting:", array_1d)

Sorted 1D Array: [1 1 2 3 4 5 5 6 9]
Original 1D Array After Sorting: [3 1 4 1 5 9 2 6 5]



##### **Example 2: Sorting a 2D Array Along Rows**


In [88]:
# Create a 2D array
array_2d = np.array([[3, 1, 4], [7, 5, 9], [2, 6, 8]])
print("Original 2D Array:\n", array_2d)

Original 2D Array:
 [[3 1 4]
 [7 5 9]
 [2 6 8]]


In [89]:
# Sort along rows (axis=0)
sorted_rows = np.sort(array_2d, axis=0)
print("Sorted along rows:\n", sorted_rows)

Sorted along rows:
 [[2 1 4]
 [3 5 8]
 [7 6 9]]


##### **Example 3: Sorting a 2D Array Along Columns**


In [90]:
# Create a 2D array
array_2d = np.array([[3, 1, 4], [7, 5, 9], [2, 6, 8]])
print("Original 2D Array:\n", array_2d)

Original 2D Array:
 [[3 1 4]
 [7 5 9]
 [2 6 8]]


In [91]:
# Sort along columns (axis=1)
sorted_columns = np.sort(array_2d, axis=1)
print("Sorted along columns:\n", sorted_columns)

Sorted along columns:
 [[1 3 4]
 [5 7 9]
 [2 6 8]]


---

### **2.2 In-Place Sorting**


In-place sorting modifies the original array directly instead of returning a new sorted array. This is useful when you want to save memory by avoiding the creation of a new array.

---


#### **Examples for In-Place Sorting**

##### **Example 1: In-Place Sorting of a 1D Array**

In [92]:
# Create a 1D array
array_1d = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("Original 1D Array:", array_1d)

Original 1D Array: [3 1 4 1 5 9 2 6 5]


In [93]:
# Sort the array in-place
array_1d.sort()
print("Sorted 1D Array (in-place):", array_1d)

Sorted 1D Array (in-place): [1 1 2 3 4 5 5 6 9]


##### **Example 2: In-Place Sorting of a 2D Array Along Rows**

In [94]:
# Create a 2D array
array_2d = np.array([[3, 1, 4], [7, 5, 9], [2, 6, 8]])
print("Original 2D Array:\n", array_2d)

Original 2D Array:
 [[3 1 4]
 [7 5 9]
 [2 6 8]]


In [95]:
# Sort along rows (axis=0) in-place
array_2d.sort(axis=0)
print("Sorted along rows (in-place):\n", array_2d)

Sorted along rows (in-place):
 [[2 1 4]
 [3 5 8]
 [7 6 9]]


---

### **2.3 Inverse Sorting (Descending Order)**


To sort an array in **descending order**, you can use slicing with `[::-1]` after sorting in ascending order.

---


#### **Examples for Inverse Sorting**

##### **Example 1: Sorting a 1D Array in Descending Order**

In [96]:
# Create a 1D array
array_1d = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("Original 1D Array:", array_1d)

Original 1D Array: [3 1 4 1 5 9 2 6 5]


In [97]:
# Sort in ascending order, then reverse for descending
sorted_descending = np.sort(array_1d)[::-1]
print("Sorted in Descending Order:", sorted_descending)

Sorted in Descending Order: [9 6 5 5 4 3 2 1 1]


##### **Example 2: Sorting a 2D Array in Descending Order Along Columns**

In [98]:
# Create a 2D array
array_2d = np.array([[3, 1, 4], [7, 5, 9], [2, 6, 8]])
print("Original 2D Array:\n", array_2d)

Original 2D Array:
 [[3 1 4]
 [7 5 9]
 [2 6 8]]


In [99]:
# Sort along columns in descending order
sorted_descending_columns = np.sort(array_2d, axis=0)[::-1]
print("Sorted along columns (descending):\n", sorted_descending_columns)

Sorted along columns (descending):
 [[7 6 9]
 [3 5 8]
 [2 1 4]]



---


### **2.4 `np.argsort()`**

The [`np.argsort()`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) function returns the indices that would sort the array. This is useful for rearranging other arrays based on the sorted order.

**Syntax:**
```python
np.argsort(array, axis=-1, kind=None, order=None)
```

- **`array`**: Input array.
- **`axis`**: Axis along which to sort. Default is `-1` (last axis).
- **`kind`**: Sorting algorithm. Default is `'quicksort'`.
- **`order`**: For structured arrays, specifies the field to sort by.


In [100]:
# help(np.argsort)

---

#### **Examples for `np.argsort()`**

##### **Example 1: Getting Indices for Sorting a 1D Array**

In [101]:
# Create a 1D array
array_1d = np.array([13, 21, 44, 11, 15, 19, 12, 16, 15])
print("Original 1D Array:", array_1d)

Original 1D Array: [13 21 44 11 15 19 12 16 15]


In [102]:
# Get the indices that would sort the array
sorted_indices = np.argsort(array_1d)
print("Indices that would sort the array:", sorted_indices)

Indices that would sort the array: [3 6 0 4 8 7 5 1 2]


In [103]:
# Use the indices to rearrange the original array
print("Rearranged array using indices:", array_1d[sorted_indices])

Rearranged array using indices: [11 12 13 15 15 16 19 21 44]


---

## **3. Advanced Examples**


### **3.1 Sorting Structured Arrays**
**Example: Sorting by a Specific Field**


In [104]:
# Create a structured array
dtype = [("name", "S10"), ("age", int), ("height", float)]
data = np.array(
    [("Alice", 25, 5.5), ("Bob", 30, 5.8), ("Charlie", 20, 5.7)], dtype=dtype
)
print("dtype:\n", dtype)
print("\nOriginal Structured Array:\n", data)

dtype:
 [('name', 'S10'), ('age', <class 'int'>), ('height', <class 'float'>)]

Original Structured Array:
 [(b'Alice', 25, 5.5) (b'Bob', 30, 5.8) (b'Charlie', 20, 5.7)]


In [105]:
# Sort by age
sorted_by_age = np.sort(data, order="age")
print("Sorted by age:\n", sorted_by_age)

Sorted by age:
 [(b'Charlie', 20, 5.7) (b'Alice', 25, 5.5) (b'Bob', 30, 5.8)]


In [106]:
# Sort by height in descending order
sorted_by_height_descending = np.sort(data, order="height")[::-1]
print("Sorted by height (descending):\n", sorted_by_height_descending)

Sorted by height (descending):
 [(b'Bob', 30, 5.8) (b'Charlie', 20, 5.7) (b'Alice', 25, 5.5)]


---