# **Useful NumPy Functions**

In [1]:
import numpy as np

---

## **Table of Contents**
1. **Logical Operations**
   - `np.all()`
   - `np.any()`
2. **Conditional Operations**
   - `np.where()`
3. **Handling Missing Values**
   - `np.isnan()`
4. **Array Manipulation**
   - `np.unique()`
   - `np.argmax()` and `np.argmin()`
   - `np.clip()`
   - `np.reshape()`
5. **Mathematical Operations**
   - `np.sum()`
   - `np.mean()`
   - `np.max()` and `np.min()`
---


## **1. Logical Operations**


### **`np.all()`**


Checks if **all elements** in an array evaluate to `True` along a specified axis.

**Syntax:**
```python
np.all(array, axis=None)
```

- **`array`**: Input array.
- **`axis`**: Axis along which to check. If `None`, checks all elements in the array.


In [15]:
# Check if all elements in a 1D array are True
array_1d = np.array([True, True, False, True])
print(array_1d)
print("Are all elements True?", np.all(array_1d))

[ True  True False  True]
Are all elements True? False


In [9]:
array_2d = np.array([[True, True], [False, True], [True, True]])
print(array_2d)

[[ True  True]
 [False  True]
 [ True  True]]


In [12]:
# Check if all elements along rows in a 2D array are True
print(np.all(array_2d, axis=1, keepdims=True))

[[ True]
 [False]
 [ True]]


In [13]:
# Check if all elements along cols in a 2D array are True
print(np.all(array_2d, axis=1, keepdims=True))

[[ True]
 [False]
 [ True]]



---



### **`np.any()`**


Checks if **any element** in an array evaluates to `True` along a specified axis.

**Syntax:**
```python
np.any(array, axis=None)
```

- **`array`**: Input array.
- **`axis`**: Axis along which to check. If `None`, checks all elements in the array.


In [17]:
# Check if any element in a 1D array is True
array_1d = np.array([False, False, True, False])
print("Is any element True?", np.any(array_1d))

Is any element True? True


In [23]:
array_2d = np.array([[False, False], [True, False], [False, False]])
print(array_2d)

[[False False]
 [ True False]
 [False False]]


In [24]:
# Check if any element along columns in a 2D array is True
print(np.any(array_2d, axis=0, keepdims=True))

[[ True False]]


In [25]:
# Check if any element along rows in a 2D array is True
print(np.any(array_2d, axis=1, keepdims=True))

[[False]
 [ True]
 [False]]



---



## **2. Conditional Operations**



### **`np.where()`**


Returns the indices or values where a condition is `True`. It can also replace values based on a condition.

**Syntax:**
```python
np.where(condition, x, y)
```

- **`condition`**: Condition to check.
- **`x`**: Values to return where the condition is `True`.
- **`y`**: Values to return where the condition is `False`.


In [27]:
# Find indices where elements are greater than 3
array_1d = np.array([1, 2, 3, 4, 5])
print("Indices where elements > 3:", np.where(array_1d > 3))

Indices where elements > 3: (array([3, 4], dtype=int64),)


In [29]:
# Replace elements greater than 3 with 10, otherwise keep the original value
print("Array after replacement:", np.where(array_1d > 3, 10, array_1d))

Array after replacement: [ 1  2  3 10 10]



---



## **3. Handling Missing Values**


### **`np.isnan()`**

Checks for **NaN (Not a Number)** values in an array and returns a boolean array.

**Syntax:**
```python
np.isnan(array)
```

- **`array`**: Input array.


In [31]:
# Check for NaN values in a 1D array
array_1d = np.array([1, 2, np.nan, 4, np.nan])
print("Is NaN?", np.isnan(array_1d))

Is NaN? [False False  True False  True]


In [32]:
# Replace NaN values with 0
array_1d[np.isnan(array_1d)] = 0
print("Array after replacing NaN with 0:", array_1d)

Array after replacing NaN with 0: [1. 2. 0. 4. 0.]



---



## **4. Array Manipulation**



### **`np.unique()`**


Returns the **unique elements** in an array, sorted in ascending order.

**Syntax:**
```python
np.unique(array, return_index=False, return_counts=False)
```

- **`array`**: Input array.
- **`return_index`**: If `True`, returns the indices of the first occurrences of the unique elements.
- **`return_counts`**: If `True`, returns the counts of each unique element.


In [ ]:
# Find unique elements in a 1D array
array_1d = np.array([1, 2, 2, 3, 3, 3, 4])
print("Unique elements:", np.unique(array_1d))

Unique elements: [1 2 3 4]


In [35]:
# Find unique elements with indices and counts
unique_elements, indices, counts = np.unique(
    array_1d, return_index=True, return_counts=True
)

print("Indices of first occurrences:", indices)
print("Counts of unique elements:", counts)

Indices of first occurrences: [0 1 3 6]
Counts of unique elements: [1 2 3 1]



---


### **`np.argmax()` and `np.argmin()`**

Returns the **indices of the maximum and minimum values** along an axis.

**Syntax:**
```python
np.argmax(array, axis=None)
np.argmin(array, axis=None)
```

- **`array`**: Input array.
- **`axis`**: Axis along which to find the indices. If `None`, works on the flattened array.


In [37]:
# Find index of maximum and minimum in a 1D array
array_1d = np.array([1, 5, 3, 9, 2])
print("Index of maximum value:", np.argmax(array_1d))  # Output: 3
print("Index of minimum value:", np.argmin(array_1d))  # Output: 0

Index of maximum value: 3
Index of minimum value: 0


In [44]:
array_2d = np.array([[1, 5, 3], [9, 2, 8], [4, 7, 6]])
print(array_2d)

[[1 5 3]
 [9 2 8]
 [4 7 6]]


In [ ]:
# Find indices of maximum and minimum along rows in a 2D array
print(
    "Indices of maximum values along rows:\n",
    np.argmax(array_2d, axis=1, keepdims=True),
)

print(
    "Indices of minimum values along rows:\n",
    np.argmin(array_2d, axis=1, keepdims=True),
)

Indices of maximum values along rows:
 [[1]
 [0]
 [1]]
Indices of minimum values along rows:
 [[0]
 [1]
 [0]]


In [ ]:
# Find indices of maximum and minimum along cols in a 2D array
print(
    "Indices of maximum values along rows:\n",
    np.argmax(array_2d, axis=0, keepdims=True),
)

print(
    "Indices of minimum values along rows:\n",
    np.argmin(array_2d, axis=0, keepdims=True),
)

Indices of maximum values along rows:
 [[1 2 1]]
Indices of minimum values along rows:
 [[0 1 0]]



---


### **`np.clip()`**


Limits the values in an array to a specified range.

**Syntax:**
```python
np.clip(array, min, max)
```

- **`array`**: Input array.
- **`min`**: Minimum value.
- **`max`**: Maximum value.


In [48]:
# Clip values in a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("Clipped array:", np.clip(array_1d, a_min=2, a_max=4))

Clipped array: [2 2 3 4 4]



---



### **`np.reshape()`**


Changes the shape of an array without changing its data.

**Syntax:**
```python
np.reshape(array, new_shape)
```

- **`array`**: Input array.
- **`new_shape`**: New shape (must be compatible with the original shape).


In [50]:
# Reshape a 1D array to a 2D array
array_1d = np.array([1, 2, 3, 4, 5, 6])
print("Reshaped array:\n", np.reshape(array_1d, (2, 3)))

Reshaped array:
 [[1 2 3]
 [4 5 6]]



---



## **5. Mathematical Operations**



### **`np.sum()`**


Computes the sum of array elements along a specified axis.

**Syntax:**
```python
np.sum(array, axis=None)
```

- **`array`**: Input array.
- **`axis`**: Axis along which to compute the sum. If `None`, sums all elements.


In [51]:
# Sum of all elements in a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("Sum of all elements:", np.sum(array_1d))

Sum of all elements: 15


In [53]:
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d)

[[1 2]
 [3 4]
 [5 6]]


In [57]:
# Sum along rows in a 2D array
print("Sum along rows:\n", np.sum(array_2d, axis=1, keepdims=True))

Sum along rows:
 [[ 3]
 [ 7]
 [11]]


In [59]:
# Sum along cols in a 2D array
print("Sum along cols:", np.sum(array_2d, axis=0))

Sum along cols: [ 9 12]



---



### **`np.mean()`**


Computes the mean of array elements along a specified axis.

**Syntax:**
```python
np.mean(array, axis=None)
```

- **`array`**: Input array.
- **`axis`**: Axis along which to compute the mean. If `None`, computes the mean of all elements.


In [62]:
# Mean of all elements in a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("Mean of all elements:", np.mean(array_1d))

Mean of all elements: 3.0


In [63]:
# Mean along columns in a 2D array
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("Mean along columns:", np.mean(array_2d, axis=0))

Mean along columns: [3. 4.]



---



### **`np.max()` and `np.min()`**


Returns the **maximum and minimum values** along a specified axis.

**Syntax:**
```python
np.max(array, axis=None)
np.min(array, axis=None)
```

- **`array`**: Input array.
- **`axis`**: Axis along which to find the max/min. If `None`, works on the flattened array.


In [ ]:
# Maximum and minimum in a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("Maximum value:", np.max(array_1d))
print("Minimum value:", np.min(array_1d))

Maximum value: 5
Minimum value: 1


In [66]:
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print(array_2d)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Maximum and minimum along columns in a 2D array
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
print("Maximum along columns:", np.max(array_2d, axis=0))
print("Minimum along columns:", np.min(array_2d, axis=0))

Maximum along columns: [5 6]
Minimum along columns: [1 2]


---