## **Numpy**

---


### **Table of Contents**

1. install and import numpy
2. 1Dimension array with features
3. 2Dimension array with features
4. Save and load array
5. Array of zeros
6. Array of Ones
7. Array of a Constant Value
8. Identity , diagonal Matrix
9. Range
10. linspace
11. Reshape
12. Random
13. Array Indexing , Modify
14. Delete Elements
15. Append
16. Insert
17. Condations
18. Sort
19. Arithmetic Operations
20. Flatt array


---

### install and import numpy


In [1]:
# !pip install numpy

In [2]:
import numpy as np

---


### 1Dimension array with features


In [3]:
# Creating a simple numpy array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [4]:
# Checking the data type of the array
print(a.dtype)
a.dtype

int32


dtype('int32')

In [5]:
# Checking the shape of the array
print(a.shape)

(5,)


In [6]:
# Get number of elements
print(a.size)

5


In [7]:
# Get itemsize
print(a.itemsize)

4


In [8]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

20
20


In [9]:
# Num of Dimension
print("ndim:", a.ndim)

ndim: 1


---


### 2Dimension array with features


In [10]:
# Creating a 2D numpy array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
# Num of Dimension
print("ndim:", a.ndim)

ndim: 2


In [12]:
# Checking the shape of the 2D array
print(a.shape)  # (rows, cols)

(2, 3)


In [13]:
# Get number of elements
print(a.size)

6


In [14]:
# Get itemsize
print(a.itemsize)

4


---


### Save and Load NumPy Array


In [15]:
# Saving the array to a file
np.save("my_array", a)

In [16]:
# Loading the array from the file
x = np.load("my_array.npy")
print(x)

[[1 2 3]
 [4 5 6]]


---


### Array of zeros


In [17]:
# Creating a NumPy array of zeroes with a specified shape
a = np.zeros((3, 4))
print(a)
print("dtype:", a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dtype: float64


In [18]:
# Creating a NumPy array of zeroes with integer type
a = np.zeros((2, 3), dtype=int)
print(a)
print("dtype:", a.dtype)
a.dtype

[[0 0 0]
 [0 0 0]]
dtype: int32


dtype('int32')

---


### Array of Ones


In [19]:
# Creating a NumPy array of ones
a = np.ones((3, 4), dtype=int)
print(a)
print("dtype:", a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
dtype: int32


---


### Array of a Constant Value


In [20]:
# Creating an array filled with a constant value
a = np.full((2, 3), 5)
print(a)
print("dtype:", a.dtype)

[[5 5 5]
 [5 5 5]]
dtype: int32


In [21]:
# Creating an array filled with a constant value and specifying the type
a = np.full((2, 3), 5, dtype=float)
print(a)
print("dtype:", a.dtype)

[[5. 5. 5.]
 [5. 5. 5.]]
dtype: float64


---


### Identity , diagonal Matrix


In [22]:
# Creating an identity matrix
a = np.eye(3, dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
# Creating an identity matrix with a specific diagonal value
a = np.eye(3, dtype=int) * 5
print(a)

[[5 0 0]
 [0 5 0]
 [0 0 5]]


In [24]:
# Creating a diagonal matrix using `diag`
a = np.diag([1, 1, 1])
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
# Creating a diagonal matrix using `diag`
a = np.diag([9, 9, 9])
print(a)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


---


### Range


In [26]:
# Generate arrays with specific numerical ranges
# arange(end) -> "start = 0"
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
# arange(start, end)
a = np.arange(4, 10)
print(a)

[4 5 6 7 8 9]


In [28]:
# arange(start, end, step)
a = np.arange(4, 10, 2)
print(a)

[4 6 8]


In [29]:
# arange with non-integer steps
a = np.arange(4, 10, 0.5)
print(a)

[4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


---


### linspace


In [30]:
# linspace with different range
# linspace(start, end, n) -> `n = number of items`

a = np.linspace(0, 25, 10)
print(a)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [31]:
# linspace with different range and endpoint set to False
a = np.linspace(0, 1, 10, endpoint=False)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


---


### Reshape


In [32]:
# Reshape array
a = np.arange(20)
a = a.reshape((4, 5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [70]:
np.arange(20).reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

---


### Random


In [33]:
# Create NumPy arrays that contain random numbers
a = np.random.random(5)  # 0:1
print(a)

[0.30613343 0.63852186 0.86993951 0.10477777 0.50079905]


In [34]:
# Create a 3x3 array of random numbers from a normal distribution
a = np.random.normal(0, 0.1, size=(3, 3))
print(a)

[[ 0.01389912 -0.00354964 -0.06508721]
 [ 0.05809937 -0.0631763   0.16545772]
 [ 0.0853344  -0.04269457 -0.15216285]]


---


### Array Indexing , Modify


In [35]:
# Creating a simple numpy array
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [36]:
# Accessing elements in the array
print("1st element:", a[0])
print("2nd element:", a[1])
print("5th element:", a[4])
print("1st element (negative index):", a[-5])
print("2nd element (negative index):", a[-4])
print("5th element (negative index):", a[-1])

1st element: 0
2nd element: 1
5th element: 4
1st element (negative index): 1
2nd element (negative index): 2
5th element (negative index): 5


In [37]:
# Modifying an element in the array
a[3] = 20
print(a)

[ 0  1  2 20  4  5]


In [38]:
# Creating and reshaping a numpy array
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
# Accessing elements in the 2D array [row , col]
print("element at (0, 0):", a[0, 0])
print("element at (0, 1):", a[0, 1])
print("element at (2, 2):", a[2, 2])

element at (0, 0): 0
element at (0, 1): 1
element at (2, 2): 8


In [40]:
#  an elemModifyingent in the 2D array
a[0, 0] = 20
print(a)

[[20  1  2]
 [ 3  4  5]
 [ 6  7  8]]


---


### Delete Elements


In [71]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [72]:
# Deleting elements from an array [row , col]
a = np.delete(a, [0, 4])
print(a)

[1 2 3 5]


In [42]:
# Deleting rows and columns from a 2D array
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
# Delete the first row
a = np.delete(a, 0, axis=0)
print("\n", a)


 [[4 5 6]
 [7 8 9]]


In [44]:
# Delete the first and last columns
a = np.delete(a, [0, 2], axis=1)
print("\n", a)


 [[5]
 [8]]


---


### Append


In [45]:
# Appending elements to an array
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

a = np.append(a, 6)
print(a)

[0 1 2 3 4 5]
[0 1 2 3 4 5 6]


In [46]:
#  multipleAppending elements to an array
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

a = np.append(a, [6, 7, 8])
print(a)

[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8]


In [47]:
# Appending a row to a 2D array
a = np.arange(1, 10).reshape(3, 3)
print(a)
a = np.append(a, [[10, 11, 12]], axis=0)
print("\n", a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [48]:
# Appending a column to a 2D array
a = np.arange(1, 10).reshape(3, 3)
print(a)

a = np.append(a, [[10], [11], [12]], axis=1)
print("\n", a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


---


### Insert


In [49]:
# Inserting values into an array
a = np.array([1, 2, 5])
print(a)

a = np.insert(a, 2, [3, 4])
print(a)

[1 2 5]
[1 2 3 4 5]


In [50]:
# Inserting a row into a 2D array
a = np.arange(1, 10).reshape(3, 3)
print(a)
a = np.insert(a, 1, [10, 11, 12], axis=0)
print("\n", a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


In [51]:
# Inserting a column into a 2D array
a = np.arange(1, 10).reshape(3, 3)
print(a)
a = np.insert(a, 1, [10, 11, 12], axis=1)
print("\n", a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1 10  2  3]
 [ 4 11  5  6]
 [ 7 12  8  9]]


In [52]:
x = np.array([1, 2])
y = np.array([[3, 4], [5, 6]])

print(x)
print("\n")
print(y)

[1 2]


[[3 4]
 [5 6]]


In [53]:
# Vertical stacking of arrays
a = np.vstack((x, y))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [54]:
# Horizontal stacking of arrays
a = np.hstack((x.reshape(2, 1), y))
print(a)

[[1 3 4]
 [2 5 6]]


---


### Condations


In [55]:
a = np.arange(25).reshape(5, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [56]:
# Boolean indexing
print(a[a > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [57]:
print(a[a <= 10])

[ 0  1  2  3  4  5  6  7  8  9 10]


In [58]:
print(a[(a > 10) & (a < 20)])

[11 12 13 14 15 16 17 18 19]


---


### Sort


In [59]:
# Sorting arrays
a = np.array([1, 6, 2, 8, 3, 7, 4, 9, 5])
print(a)
a.sort()
print(a)

[1 6 2 8 3 7 4 9 5]
[1 2 3 4 5 6 7 8 9]


In [60]:
# Sorting 2D arrays
a = np.random.randint(1, 20, size=(5, 5))
print(a)

[[10  2  3 16 19]
 [15 18  9  6 15]
 [19 19 10  7  9]
 [12  7 15 13  2]
 [ 2  7  3  6 15]]


In [61]:
# Sorting by columns
print(np.sort(a, axis=0))

[[ 2  2  3  6  2]
 [10  7  3  6  9]
 [12  7  9  7 15]
 [15 18 10 13 15]
 [19 19 15 16 19]]


In [62]:
# Sorting by rows
print(np.sort(a, axis=1))

[[ 2  3 10 16 19]
 [ 6  9 15 15 18]
 [ 7  9 10 19 19]
 [ 2  7 12 13 15]
 [ 2  3  6  7 15]]


---


### Arithmetic Operations


In [63]:
# Arithmetic Operations
x = np.array([10, 20, 30])
y = np.array([5, 2, 4])

print(x + y)
print(np.add(x, y))
print("\n")

print(x - y)
print(np.subtract(x, y))
print("\n")

print(x * y)
print(np.multiply(x, y))
print("\n")

print(x / y)
print(np.divide(x, y))

[15 22 34]
[15 22 34]


[ 5 18 26]
[ 5 18 26]


[ 50  40 120]
[ 50  40 120]


[ 2.  10.   7.5]
[ 2.  10.   7.5]


> must be same shape


In [64]:
# 2D array
x = np.array([[1, 4], [5, 9]])
y = np.array([[2, 7], [10, 5]])


print(x + y)  # result [ [3, 11], [15, 14] ]
print("\n", x - y)  # result [ [-1, -3], [-5, 4] ]
print("\n", x * y)  # result [ [2, 28], [50, 45] ]
print("\n", x / y)  # result [ [0.5, 0.57142857], [0.5, 1.8] ]

[[ 3 11]
 [15 14]]

 [[-1 -3]
 [-5  4]]

 [[ 2 28]
 [50 45]]

 [[0.5        0.57142857]
 [0.5        1.8       ]]


In [65]:
# Min, Max, Sum
a = np.array([10, 20, 30])
print(a.min())
print(a.max())
print(a.sum())

10
30
60


In [66]:
a = np.array([[6, 4], [3, 9]])
print(a.min())
print(a.max())
print(a.sum())

3
9
22


In [67]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


---


### Flatt array


In [68]:
# ravel() => Returns Flattened Array 1 Dimension With Same Type
a = np.array([[6, 4], [3, 9]])
print(a.ravel())

[6 4 3 9]


In [69]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
print("ndim", a.ndim)
print("\n")

a = a.ravel()
print(a)
print("ndim", a.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim 3


[1 2 3 4 5 6 7 8]
ndim 1


---
